class TelegramBot {
    - token: str
    - parse_mode: str
    + start()
    + stop()
}

class BotDispatcher {
    + include_routers(routers: list)
    + start_polling(bot: TelegramBot)
}

class Router {
    + message(handler: Callable)
    + callback_query(handler: Callable)
}

class MessageHandler {
    + handle_message(message: Message)
}

class CallbackQueryHandler {
    + handle_callback_query(callback_query: CallbackQuery)
}

class Database {
    + query(sql: str)
    + commit()
}

class CustomKeyboards {
    + get_org_keyboard(): InlineKeyboardMarkup
    + get_cp_kb(): InlineKeyboardMarkup
    + get_name_cp_kb(): InlineKeyboardMarkup
    + get_start_kb(): ReplyKeyboardMarkup
}

TelegramBot --> BotDispatcher : управляет
BotDispatcher --> Router : использует
Router --> MessageHandler : обрабатывает
Router --> CallbackQueryHandler : обрабатывает
MessageHandler <--> Database : обращается к базе данных
CallbackQueryHandler <--> Database : обращается к базе данных
CustomKeyboards --> Router : создает