@startuml
start
:Нажать на кнопку "СММ";
:Нажать на дату;
:Отобразить список постов, которые нужно сделать;
if (Редактировать посты?) then (да)
  :Отобразить форму редактирования;
  :Сохранить изменения;
endif
stop
@enduml
