@startuml
[*] --> Idle

Idle : Ожидание команды
Idle --> FetchingSMMData : Нажата кнопка "СММ"
FetchingSMMData : Получение данных о постах
FetchingSMMData --> DisplayingSMMData : Данные о постах получены
DisplayingSMMData : Отображение данных о постах
DisplayingSMMData --> Idle : Ожидание следующей команды
@enduml
