@startuml
left to right direction
actor User as U
rectangle "Театральное приложение" {
    usecase "Просмотр информации о должностных лицах" as A
    usecase "Просмотр информации об контент-плане" as B
    usecase "Просмотр информации о постановках" as C
    usecase "Просмотр информации о треннингах" as D
    U --> (A)
    U --> (B)
    U --> (C)
    U --> (D)
}
@enduml