@startuml
start
:Нажать на кнопку "Постановки";
:Отобразить список месяцев;
:Выбрать месяц;
:Отобразить постановки на выбранный месяц;
:Выбрать постановку;
if (Редактировать постановку?) then (да)
  :Отобразить форму редактирования;
  :Сохранить изменения;
endif
stop
@enduml
