@startuml
[*] --> Idle

Idle : Ожидание команды
Idle --> FetchingTrainings : Нажата кнопка "Тренинги"
FetchingTrainings : Получение информации о тренингах
FetchingTrainings --> DisplayingTrainings : Информация получена
DisplayingTrainings : Отображение информации о тренингах
DisplayingTrainings --> Idle : Ожидание следующей команды

FetchEditTraining : Редактирование тренинга
FetchEditTraining --> Idle : Отмена
FetchEditTraining --> EditingTrainingInfo : Подтверждение

EditingTrainingInfo : Редактирование тренинга
EditingTrainingInfo --> Idle : Завершение
@enduml
